### ISSUE TITLE
Use CJK decomposition data

### ISSUE THREAD

**Issue by mathewthe2** [jhgjeraker/bunshi#2]
Can you add CJK decomposition to visualize the breakdown for intermediaries between kanji and radicals?

Examples:
https://www.kakimashou.com/dictionary/character/%E6%BC%A2
https://www.kanshudo.com/search?q=%E6%BC%A2

Related data:
https://github.com/amake/cjk-decomp
https://github.com/cjkvi/cjkvi-ids

**Comment by jhgjeraker** [comment]
Interesting suggestion. Take a look at the linked branch `cjk-decomposition-data` where I had a go at it. Is this in the realms of what you had in mind?

With the new changes, the output is currently something like this:
```
そうですね、住んでいるところで猫が飼う
          │    │         │  └ 飼, domesticate
          │    │         │    ├ 飠, eat
          │    │         │    │ ├ 人, person
          │    │         │    │ ├ 丶, dot
          │    │         │    │ └ ⑤,
          │    │         │    ├ 司, director
          │    │         │    │ ├ 𠃌,
          │    │         │    │ └ 𠮛,
          │    │         │    │   ├ 一, one
          │    │         │    │   └ 口, mouth
          │    │         │    └ 𩙿,
          │    │         └ 猫, cat
          │    │           ├ 犭, dog
          │    │           └ 苗, seedling
          │    │             ├ 艹,
          │    │             │ ├ 十, ten
          │    │             │ └ 丨, line
          │    │             └ 田, rice paddy
          │    └ い,
          └ 住, dwelling
            ├ 亻, man
            └ 主, master
              ├ 亠, lid
              │ ├ 丶, dot
              │ ├ 一, one
              │ └ 丨, line
              ├ 土, soil
              │ ├ 十, ten
              │ └ 一, one
              ├ 丶, dot
              └ 王, king
                ├ 一, one
                └ 土, soil
                  ├ 十, ten
                  └ 一, one
```

Compared to the previous 1 level, the decomposition will now keep going dynamically until all levels are resolved. I used the data in [cjkvi-ids](https://github.com/cjkvi/cjkvi-ids) as a source.

As you can see there are a few quirks with the source data, like `い` being recognized as a decomposition root, but that can be cleaned up.

Thoughts?

Please give it a try by checking out the branch!

**Comment by mathewthe2** [comment]
Nice job. There is some discrepancy between what the online websites provide.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/13146030/187926417-9dde85f8-748d-4267-8dbb-49c01b1a3c60.png">

Not sure if they are using another data source or they did some heavy cleaning of this dataset.

**Comment by jhgjeraker** [comment]
They are likely using a combination of different sources, some proprietary, some manually vetted. I'll stick with open-source material in this project, so I probably won't be able to match the output completely.

Not all the various dictionaries agree on the breakdowns anyways. If you compare [kakimashou](https://www.kakimashou.com/dictionary/character/%E9%A3%BC) to [kanshudo](https://www.kanshudo.com/search?q=%E9%A3%BC) they are quite different.

I'll do a quick vetting of the source material to remove the low hanging fruit, then I'll probably merge the branch into main when I get time.
